name: Deploy Portfolio

on:
  push:
    branches:
      - main  # Change this to your default branch, e.g., 'main' or 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step to check out the code from the repo
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step to set up Node.js (add the version you're using)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Change this to the version of Node.js you're using

      # Step to install dependencies
      - name: Install dependencies
        run: |
          npm install
          npm install --save-dev @babel/plugin-proposal-private-property-in-object
          npm install @emotion/react

      # Step to build the app
      - name: Build the app
        run: npm run build

      # Step to deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        run: npm run deploy
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
